language: node_js
node_js:
  - 12
env:
  global:
    - CC_TEST_REPORTER_ID=0c0f562adec669b8f4aed91a94cda433f3605dcc68554cebb11fbf434da552ca

install:
  - npm ci
cache:
  directories:
    - '$HOME/.npm'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

script:
  - npm test
